name: Classes Scrapper

on:
  workflow_dispatch:
    
  schedule:
    - cron: "30 12-15 * * 4"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Set env vars
        run: |
          echo "URL=${URL}" > .env
          echo "TEACHER_NAME=${TEACHER_NAME}" >> .env
          echo "ORGANIZATION_NAME=${ORGANIZATION_NAME}" >> .env
          echo "GMAIL_ACCOUNT=${GMAIL_ACCOUNT}" >> .env
          echo "ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}" >> .env
          cat .env  
      - name: Run the scrapper  
        run: |
          set -a; source .env; set +a;
          npm i
          npm start
